// vue-todo/src/components/Header.vue
<template>
  <header class="grid--header">
    <div class="logo">
      <Logo />
    </div>
    <div class="list-info">
      <div class="list-info__content">
        <ListTitle :title="title" />
        <TodosLeft />
        <ProgressBar :current="current" :max="max" />
      </div>
    </div>
  </header>
</template>

<script>
import { store } from '../store/index.js'
import dateTitle from '../helpers/dateFormat'
import Logo from './Logo'
import ListTitle from './ListTitle'
import ProgressBar from './ProgressBar'
import TodosLeft from './TodosLeft'

export default {
  name: 'Header',
  components: {
    Logo,
    ProgressBar,
    ListTitle,
    TodosLeft
  },
  data() {
    return {
      title: dateTitle(new Date()),
    }
  },
  computed: {
    current() {
      return store.getters.completedTodos
    },
    max() {
      return store.getters.totalTodos
    }
  },
}
</script>

<style lang="scss" scoped>
.logo {
  display: flex;
  align-items: center;
  grid-area: logo;
  padding: $spacing;
}
.list-info {
  padding: ($spacing * 2) $spacing;
  grid-area: list-info;

  &__content {
    display: inline-block;
  }
}
</style>

// svelte-todo/src/components/Header.svelte
<script>
import Title from './Title.svelte'
import TodayTitle from './TodayTitle.svelte'
</script>

<style>
header {
  display: grid;
  grid-template-columns: minmax(20px, 300px) 1fr;
  grid-template-rows: 1fr;
  grid-template-areas: "logo list-info";
  grid-area: header;
}
.logo {
  display: flex;
  align-items: center;
  grid-area: logo;
  padding: var(--spacing);
}
.list-info {
  display: flex;
  align-items: center;
  padding: var(--spacing);
  grid-area: list-info;
}
</style>

<header>
  <div class="logo">
    <Title />
  </div>
  <div class="list-info">
    <TodayTitle />
  </div>
</header>
